In [24]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
import pickle
import joblib
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import seaborn as sn
from sklearn import datasets
from sklearn.preprocessing import LabelEncoder
from sklearn import tree
from sklearn import svm
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

digits = datasets.load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [25]:
cross_val_score(linear_model.LinearRegression(), digits.data, digits.target)

array([0.48346048, 0.5583603 , 0.57534522, 0.5056632 , 0.40995457])

In [26]:
cross_val_score(svm.SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [27]:
cross_val_score(tree.DecisionTreeClassifier(), digits.data, digits.target)

array([0.78333333, 0.70833333, 0.81058496, 0.83286908, 0.79665738])

In [28]:
cross_val_score(ensemble.RandomForestClassifier(n_estimators=35), digits.data, digits.target)

array([0.95      , 0.89166667, 0.95821727, 0.9637883 , 0.92479109])

In [29]:
np.mean(cross_val_score(linear_model.LinearRegression(), digits.data, digits.target))

0.5065567550630679

In [30]:
np.mean(cross_val_score(svm.SVC(), digits.data, digits.target))

0.9632838130609718

In [31]:
np.mean(cross_val_score(ensemble.RandomForestClassifier(n_estimators=45), digits.data, digits.target))

0.9410259981429897

In [32]:
np.mean(cross_val_score(tree.DecisionTreeClassifier(), digits.data, digits.target))

0.7835701021355617